// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BatchActionApprovals implements batchActionApprovals operation.
//
// Approve or reject multiple approvals.
//
// POST /api/operator/approvals/batch
func (UnimplementedHandler) BatchActionApprovals(ctx context.Context, req *BatchApprovalRequest) (r BatchActionApprovalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApp implements deleteApp operation.
//
// Delete an app; starts persistence grace period.
//
// DELETE /api/repos/{org}/{repo}/apps/{name}
func (UnimplementedHandler) DeleteApp(ctx context.Context, params DeleteAppParams) (r DeleteAppRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRepo implements deleteRepo operation.
//
// Delete all apps in a repo.
//
// DELETE /api/repos/{org}/{repo}
func (UnimplementedHandler) DeleteRepo(ctx context.Context, params DeleteRepoParams) (r DeleteRepoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApp implements getApp operation.
//
// Get app detail.
//
// GET /api/repos/{org}/{repo}/apps/{name}
func (UnimplementedHandler) GetApp(ctx context.Context, params GetAppParams) (r GetAppRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAppHistory implements getAppHistory operation.
//
// Get deploy history for an app.
//
// GET /api/repos/{org}/{repo}/apps/{name}/history
func (UnimplementedHandler) GetAppHistory(ctx context.Context, params GetAppHistoryParams) (r GetAppHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAppStatus implements getAppStatus operation.
//
// Get current runtime state of an app.
//
// GET /api/repos/{org}/{repo}/apps/{name}/status
func (UnimplementedHandler) GetAppStatus(ctx context.Context, params GetAppStatusParams) (r GetAppStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAppUtilisation implements getAppUtilisation operation.
//
// Get current resource usage and cost estimate for an app.
//
// GET /api/repos/{org}/{repo}/apps/{name}/utilisation
func (UnimplementedHandler) GetAppUtilisation(ctx context.Context, params GetAppUtilisationParams) (r GetAppUtilisationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthz implements getHealthz operation.
//
// Health check.
//
// GET /healthz
func (UnimplementedHandler) GetHealthz(ctx context.Context) (r *GetHealthzOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOperation implements getOperation operation.
//
// Poll an async operation.
//
// GET /api/repos/{org}/{repo}/apps/{name}/operations/{id}
func (UnimplementedHandler) GetOperation(ctx context.Context, params GetOperationParams) (r GetOperationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOperatorApproval implements getOperatorApproval operation.
//
// Get single approval detail.
//
// GET /api/operator/approvals/{id}
func (UnimplementedHandler) GetOperatorApproval(ctx context.Context, params GetOperatorApprovalParams) (r GetOperatorApprovalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOperatorConfig implements getOperatorConfig operation.
//
// Read platform config.
//
// GET /api/operator/config
func (UnimplementedHandler) GetOperatorConfig(ctx context.Context) (r GetOperatorConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOperatorCost implements getOperatorCost operation.
//
// Platform-wide cost estimate.
//
// GET /api/operator/cost
func (UnimplementedHandler) GetOperatorCost(ctx context.Context) (r GetOperatorCostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOperatorStatus implements getOperatorStatus operation.
//
// Platform health summary.
//
// GET /api/operator/status
func (UnimplementedHandler) GetOperatorStatus(ctx context.Context) (r GetOperatorStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRepo implements getRepo operation.
//
// Get repo detail including tier and quota.
//
// GET /api/repos/{org}/{repo}
func (UnimplementedHandler) GetRepo(ctx context.Context, params GetRepoParams) (r GetRepoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HibernateApp implements hibernateApp operation.
//
// Force hibernate an app.
//
// POST /api/repos/{org}/{repo}/apps/{name}/hibernate
func (UnimplementedHandler) HibernateApp(ctx context.Context, params HibernateAppParams) (r HibernateAppRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListApps implements listApps operation.
//
// List apps in a repo.
//
// GET /api/repos/{org}/{repo}/apps
func (UnimplementedHandler) ListApps(ctx context.Context, params ListAppsParams) (r ListAppsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOperatorApprovals implements listOperatorApprovals operation.
//
// List all pending approvals.
//
// GET /api/operator/approvals
func (UnimplementedHandler) ListOperatorApprovals(ctx context.Context) (r ListOperatorApprovalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRepoApprovals implements listRepoApprovals operation.
//
// List pending approvals for a repo.
//
// GET /api/repos/{org}/{repo}/approvals
func (UnimplementedHandler) ListRepoApprovals(ctx context.Context, params ListRepoApprovalsParams) (r ListRepoApprovalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRepos implements listRepos operation.
//
// List repos.
//
// GET /api/repos
func (UnimplementedHandler) ListRepos(ctx context.Context, params ListReposParams) (r ListReposRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SyncRepo implements syncRepo operation.
//
// Declarative app list reconciliation; detects deleted apps.
//
// POST /api/repos/{org}/{repo}/sync
func (UnimplementedHandler) SyncRepo(ctx context.Context, req *SyncRequest, params SyncRepoParams) (r SyncRepoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TokenDeploy implements tokenDeploy operation.
//
// Exchange a deploy identity token for a developer access token.
//
// POST /api/token/deploy
func (UnimplementedHandler) TokenDeploy(ctx context.Context, req *TokenDeployReq) (r TokenDeployRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TokenOIDC implements tokenOIDC operation.
//
// Exchange a platform identity credential for an operator access token and refresh token.
//
// POST /api/token/oidc
func (UnimplementedHandler) TokenOIDC(ctx context.Context, req *TokenOIDCReq) (r TokenOIDCRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TokenRefresh implements tokenRefresh operation.
//
// Exchange a refresh token for a new access token and rotated refresh token.
//
// POST /api/token/refresh
func (UnimplementedHandler) TokenRefresh(ctx context.Context, req *TokenRefreshReq) (r TokenRefreshRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOperatorConfig implements updateOperatorConfig operation.
//
// Update mutable platform config.
//
// PATCH /api/operator/config
func (UnimplementedHandler) UpdateOperatorConfig(ctx context.Context, req *PlatformConfig) (r UpdateOperatorConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRepoTier implements updateRepoTier operation.
//
// Promote or demote repo tier.
//
// PATCH /api/operator/repos/{org}/{repo}
func (UnimplementedHandler) UpdateRepoTier(ctx context.Context, req *UpdateRepoTierRequest, params UpdateRepoTierParams) (r UpdateRepoTierRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertApp implements upsertApp operation.
//
// Upsert an app; runs staging handshake and applies Kubernetes manifest.
//
// POST /api/repos/{org}/{repo}/apps
func (UnimplementedHandler) UpsertApp(ctx context.Context, req *AppSpec, params UpsertAppParams) (r UpsertAppRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WakeApp implements wakeApp operation.
//
// Force wake a hibernated app.
//
// POST /api/repos/{org}/{repo}/apps/{name}/wake
func (UnimplementedHandler) WakeApp(ctx context.Context, params WakeAppParams) (r WakeAppRes, _ error) {
	return r, ht.ErrNotImplemented
}
