// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BatchActionApprovals implements batchActionApprovals operation.
	//
	// Acts on multiple approval requests in one call. Approved changes are applied immediately; rejected
	// changes are discarded. IDs not found or already resolved appear in the ignored list.
	//
	// POST /api/operator/approvals/batch
	BatchActionApprovals(ctx context.Context, req *BatchActionApprovalsReq) (BatchActionApprovalsRes, error)
	// DeleteApp implements deleteApp operation.
	//
	// Marks the app for deletion and begins a grace period before its persistent storage is removed. Poll
	// the returned operation to track progress.
	//
	// DELETE /api/repos/{org}/{repo}/apps/{name}
	DeleteApp(ctx context.Context, params DeleteAppParams) (DeleteAppRes, error)
	// DeleteRepo implements deleteRepo operation.
	//
	// Queues deletion of every app in the repo. Returns immediately; poll the returned operation to track
	// progress. The repo record is removed once all apps are gone.
	//
	// DELETE /api/repos/{org}/{repo}
	DeleteRepo(ctx context.Context, params DeleteRepoParams) (DeleteRepoRes, error)
	// GetApp implements getApp operation.
	//
	// Returns the app's current configuration, status, and deployment timestamps.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}
	GetApp(ctx context.Context, params GetAppParams) (GetAppRes, error)
	// GetAppHistory implements getAppHistory operation.
	//
	// Returns past operations for the app in reverse chronological order, including deploys, deletes, and
	// hibernation events.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/history
	GetAppHistory(ctx context.Context, params GetAppHistoryParams) (GetAppHistoryRes, error)
	// GetAppStatus implements getAppStatus operation.
	//
	// Returns the Kubernetes-level status of the app including replica counts. Use this to determine
	// whether the app is healthy or still starting up.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/status
	GetAppStatus(ctx context.Context, params GetAppStatusParams) (GetAppStatusRes, error)
	// GetAppUtilisation implements getAppUtilisation operation.
	//
	// Returns recent CPU and memory usage averaged over the last collection window, and a projected
	// monthly cost at the current usage rate.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/utilisation
	GetAppUtilisation(ctx context.Context, params GetAppUtilisationParams) (GetAppUtilisationRes, error)
	// GetHealthz implements getHealthz operation.
	//
	// Returns 200 when the API server is up and able to handle requests. Does not check downstream
	// dependencies.
	//
	// GET /healthz
	GetHealthz(ctx context.Context) (*GetHealthzOK, error)
	// GetOperation implements getOperation operation.
	//
	// Fetch the current state of a long-running operation. Retry until status is "complete" or "failed".
	// The Retry-After header on the originating 202 response suggests a polling interval.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/operations/{id}
	GetOperation(ctx context.Context, params GetOperationParams) (GetOperationRes, error)
	// GetOperatorApproval implements getOperatorApproval operation.
	//
	// Returns the full detail of a single approval request, including the current and requested field
	// values.
	//
	// GET /api/operator/approvals/{id}
	GetOperatorApproval(ctx context.Context, params GetOperatorApprovalParams) (GetOperatorApprovalRes, error)
	// GetOperatorConfig implements getOperatorConfig operation.
	//
	// Returns the current mutable platform-wide settings, including budget limits.
	//
	// GET /api/operator/config
	GetOperatorConfig(ctx context.Context) (GetOperatorConfigRes, error)
	// GetOperatorCost implements getOperatorCost operation.
	//
	// Returns the projected monthly spend across the entire platform, broken down by repo. Figures are
	// estimates based on current resource usage and tier pricing.
	//
	// GET /api/operator/cost
	GetOperatorCost(ctx context.Context) (GetOperatorCostRes, error)
	// GetOperatorStatus implements getOperatorStatus operation.
	//
	// Returns a high-level health snapshot of the platform, including whether critical components are
	// operational and how many apps are currently running.
	//
	// GET /api/operator/status
	GetOperatorStatus(ctx context.Context) (GetOperatorStatusRes, error)
	// GetRepo implements getRepo operation.
	//
	// Returns the repo's tier, app count, and registration timestamp.
	//
	// GET /api/repos/{org}/{repo}
	GetRepo(ctx context.Context, params GetRepoParams) (GetRepoRes, error)
	// HibernateApp implements hibernateApp operation.
	//
	// Scales the app to zero replicas immediately, freeing its compute resources. The app resumes
	// automatically on the next inbound request, or can be woken explicitly via the wake endpoint.
	//
	// POST /api/repos/{org}/{repo}/apps/{name}/hibernate
	HibernateApp(ctx context.Context, params HibernateAppParams) (HibernateAppRes, error)
	// ListApps implements listApps operation.
	//
	// Returns every app currently deployed in the repo, including their status and image.
	//
	// GET /api/repos/{org}/{repo}/apps
	ListApps(ctx context.Context, params ListAppsParams) (ListAppsRes, error)
	// ListOperatorApprovals implements listOperatorApprovals operation.
	//
	// Returns every approval request across all repos that is waiting for operator action.
	//
	// GET /api/operator/approvals
	ListOperatorApprovals(ctx context.Context) (ListOperatorApprovalsRes, error)
	// ListRepoApprovals implements listRepoApprovals operation.
	//
	// Returns approval requests raised by changes to this repo that are awaiting operator action before
	// they take effect.
	//
	// GET /api/repos/{org}/{repo}/approvals
	ListRepoApprovals(ctx context.Context, params ListRepoApprovalsParams) (ListRepoApprovalsRes, error)
	// ListRepos implements listRepos operation.
	//
	// Returns repos the caller has access to. Developers see only their own repo; operators see all repos
	// by default.
	//
	// GET /api/repos
	ListRepos(ctx context.Context, params ListReposParams) (ListReposRes, error)
	// SyncRepo implements syncRepo operation.
	//
	// Reconciles the cluster against the supplied app list. Apps present in the cluster but absent from
	// the list are queued for deletion. Equivalent to calling upsert for each listed app and delete for
	// each omitted one, in a single atomic request.
	//
	// POST /api/repos/{org}/{repo}/sync
	SyncRepo(ctx context.Context, req *SyncRepoReq, params SyncRepoParams) (SyncRepoRes, error)
	// TokenDeploy implements tokenDeploy operation.
	//
	// For use in CI/CD pipelines. Present a short-lived identity token issued by your CI platform (e.g. a
	// GitHub Actions OIDC token). Returns a scoped access token valid for the duration of the deploy.
	//
	// POST /api/token/deploy
	TokenDeploy(ctx context.Context, req *TokenDeployReq) (TokenDeployRes, error)
	// TokenOIDC implements tokenOIDC operation.
	//
	// For interactive operator sessions. Exchanges a platform credential for an access/refresh token pair.
	// Use the refresh endpoint to stay authenticated without re-presenting credentials.
	//
	// POST /api/token/oidc
	TokenOIDC(ctx context.Context, req *TokenOIDCReq) (TokenOIDCRes, error)
	// TokenRefresh implements tokenRefresh operation.
	//
	// Rotates both tokens. The supplied refresh token is immediately invalidated; use the new pair going
	// forward.
	//
	// POST /api/token/refresh
	TokenRefresh(ctx context.Context, req *TokenRefreshReq) (TokenRefreshRes, error)
	// UpdateOperatorConfig implements updateOperatorConfig operation.
	//
	// Applies the supplied fields over the current config. Omitted fields are left unchanged.
	//
	// PATCH /api/operator/config
	UpdateOperatorConfig(ctx context.Context, req *PlatformConfig) (UpdateOperatorConfigRes, error)
	// UpdateRepoTier implements updateRepoTier operation.
	//
	// Changes the resource tier for a repo, which controls its compute limits and cost ceiling. Promotion
	// to a higher tier may require additional approval depending on platform policy.
	//
	// PATCH /api/operator/repos/{org}/{repo}
	UpdateRepoTier(ctx context.Context, req *UpdateRepoTierReq, params UpdateRepoTierParams) (UpdateRepoTierRes, error)
	// UpsertApp implements upsertApp operation.
	//
	// Creates or updates an app. Runs a staging handshake to validate the image before applying the
	// manifest. Some changes may require operator approval and will appear in the pending_approval field
	// of the response.
	//
	// POST /api/repos/{org}/{repo}/apps
	UpsertApp(ctx context.Context, req *AppSpec, params UpsertAppParams) (UpsertAppRes, error)
	// WakeApp implements wakeApp operation.
	//
	// Scales the app back up from zero replicas. Use this to pre-warm the app before expected traffic
	// rather than waiting for the first request to trigger wake-on-demand.
	//
	// POST /api/repos/{org}/{repo}/apps/{name}/wake
	WakeApp(ctx context.Context, params WakeAppParams) (WakeAppRes, error)
	// NewError creates *ErrorInternalServerStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorInternalServerStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
