// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn28AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn3AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn20AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn21AllowedHeaders = map[string]string{
		"GET":   "Authorization",
		"PATCH": "Authorization,Content-Type",
	}
	rn23AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn1AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn33AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
	}
	rn43AllowedHeaders = map[string]string{
		"PATCH": "Authorization,Content-Type",
	}
	rn24AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn31AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn8AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
	}
	rn30AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn27AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization,Content-Type",
	}
	rn10AllowedHeaders = map[string]string{
		"DELETE": "Authorization",
		"GET":    "Authorization",
	}
	rn26AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn11AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn18AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn13AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn14AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn44AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn35AllowedHeaders = map[string]string{
		"POST": "Authorization,Content-Type",
	}
	rn36AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn38AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn39AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [4]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/"

				if l := len("api/"); len(elem) >= l && elem[0:l] == "api/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "operator/"

					if l := len("operator/"); len(elem) >= l && elem[0:l] == "operator/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "approvals"

						if l := len("approvals"); len(elem) >= l && elem[0:l] == "approvals" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListOperatorApprovalsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn28AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'b': // Prefix: "batch"
								origElem := elem
								if l := len("batch"); len(elem) >= l && elem[0:l] == "batch" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleBatchActionApprovalsRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn3AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

								elem = origElem
							}
							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetOperatorApprovalRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn20AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'c': // Prefix: "co"

						if l := len("co"); len(elem) >= l && elem[0:l] == "co" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'n': // Prefix: "nfig"

							if l := len("nfig"); len(elem) >= l && elem[0:l] == "nfig" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetOperatorConfigRequest([0]string{}, elemIsEscaped, w, r)
								case "PATCH":
									s.handleUpdateOperatorConfigRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,PATCH",
										allowedHeaders: rn21AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}

						case 's': // Prefix: "st"

							if l := len("st"); len(elem) >= l && elem[0:l] == "st" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetOperatorCostRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn23AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'p': // Prefix: "principals"

						if l := len("principals"); len(elem) >= l && elem[0:l] == "principals" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListOperatorPrincipalsRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleAddOperatorPrincipalRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,POST",
									allowedHeaders: rn1AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "principal"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleRemoveOperatorPrincipalRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE",
										allowedHeaders: rn33AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'r': // Prefix: "repos/"

						if l := len("repos/"); len(elem) >= l && elem[0:l] == "repos/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "org"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "repo"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PATCH":
									s.handleUpdateRepoTierRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PATCH",
										allowedHeaders: rn43AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}

						}

					case 's': // Prefix: "status"

						if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetOperatorStatusRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn24AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'r': // Prefix: "repos"

					if l := len("repos"); len(elem) >= l && elem[0:l] == "repos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleListReposRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn31AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "org"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "repo"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleDeleteRepoRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetRepoRequest([2]string{
										args[0],
										args[1],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,GET",
										allowedHeaders: rn8AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "app"

									if l := len("app"); len(elem) >= l && elem[0:l] == "app" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'r': // Prefix: "rovals"

										if l := len("rovals"); len(elem) >= l && elem[0:l] == "rovals" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleListRepoApprovalsRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: rn30AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									case 's': // Prefix: "s"

										if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch r.Method {
											case "GET":
												s.handleListAppsRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											case "POST":
												s.handleUpsertAppRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET,POST",
													allowedHeaders: rn27AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "name"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[2] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												switch r.Method {
												case "DELETE":
													s.handleDeleteAppRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												case "GET":
													s.handleGetAppRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "DELETE,GET",
														allowedHeaders: rn10AllowedHeaders,
														acceptPost:     "",
														acceptPatch:    "",
													})
												}

												return
											}
											switch elem[0] {
											case '/': // Prefix: "/"

												if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													break
												}
												switch elem[0] {
												case 'h': // Prefix: "hi"

													if l := len("hi"); len(elem) >= l && elem[0:l] == "hi" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														break
													}
													switch elem[0] {
													case 'b': // Prefix: "bernate"

														if l := len("bernate"); len(elem) >= l && elem[0:l] == "bernate" {
															elem = elem[l:]
														} else {
															break
														}

														if len(elem) == 0 {
															// Leaf node.
															switch r.Method {
															case "POST":
																s.handleHibernateAppRequest([3]string{
																	args[0],
																	args[1],
																	args[2],
																}, elemIsEscaped, w, r)
															default:
																s.notAllowed(w, r, notAllowedParams{
																	allowedMethods: "POST",
																	allowedHeaders: rn26AllowedHeaders,
																	acceptPost:     "",
																	acceptPatch:    "",
																})
															}

															return
														}

													case 's': // Prefix: "story"

														if l := len("story"); len(elem) >= l && elem[0:l] == "story" {
															elem = elem[l:]
														} else {
															break
														}

														if len(elem) == 0 {
															// Leaf node.
															switch r.Method {
															case "GET":
																s.handleGetAppHistoryRequest([3]string{
																	args[0],
																	args[1],
																	args[2],
																}, elemIsEscaped, w, r)
															default:
																s.notAllowed(w, r, notAllowedParams{
																	allowedMethods: "GET",
																	allowedHeaders: rn11AllowedHeaders,
																	acceptPost:     "",
																	acceptPatch:    "",
																})
															}

															return
														}

													}

												case 'o': // Prefix: "operations/"

													if l := len("operations/"); len(elem) >= l && elem[0:l] == "operations/" {
														elem = elem[l:]
													} else {
														break
													}

													// Param: "id"
													// Leaf parameter, slashes are prohibited
													idx := strings.IndexByte(elem, '/')
													if idx >= 0 {
														break
													}
													args[3] = elem
													elem = ""

													if len(elem) == 0 {
														// Leaf node.
														switch r.Method {
														case "GET":
															s.handleGetOperationRequest([4]string{
																args[0],
																args[1],
																args[2],
																args[3],
															}, elemIsEscaped, w, r)
														default:
															s.notAllowed(w, r, notAllowedParams{
																allowedMethods: "GET",
																allowedHeaders: rn18AllowedHeaders,
																acceptPost:     "",
																acceptPatch:    "",
															})
														}

														return
													}

												case 's': // Prefix: "status"

													if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch r.Method {
														case "GET":
															s.handleGetAppStatusRequest([3]string{
																args[0],
																args[1],
																args[2],
															}, elemIsEscaped, w, r)
														default:
															s.notAllowed(w, r, notAllowedParams{
																allowedMethods: "GET",
																allowedHeaders: rn13AllowedHeaders,
																acceptPost:     "",
																acceptPatch:    "",
															})
														}

														return
													}

												case 'u': // Prefix: "utilisation"

													if l := len("utilisation"); len(elem) >= l && elem[0:l] == "utilisation" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch r.Method {
														case "GET":
															s.handleGetAppUtilisationRequest([3]string{
																args[0],
																args[1],
																args[2],
															}, elemIsEscaped, w, r)
														default:
															s.notAllowed(w, r, notAllowedParams{
																allowedMethods: "GET",
																allowedHeaders: rn14AllowedHeaders,
																acceptPost:     "",
																acceptPatch:    "",
															})
														}

														return
													}

												case 'w': // Prefix: "wake"

													if l := len("wake"); len(elem) >= l && elem[0:l] == "wake" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch r.Method {
														case "POST":
															s.handleWakeAppRequest([3]string{
																args[0],
																args[1],
																args[2],
															}, elemIsEscaped, w, r)
														default:
															s.notAllowed(w, r, notAllowedParams{
																allowedMethods: "POST",
																allowedHeaders: rn44AllowedHeaders,
																acceptPost:     "",
																acceptPatch:    "",
															})
														}

														return
													}

												}

											}

										}

									}

								case 's': // Prefix: "sync"

									if l := len("sync"); len(elem) >= l && elem[0:l] == "sync" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleSyncRepoRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn35AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						}

					}

				case 't': // Prefix: "token/"

					if l := len("token/"); len(elem) >= l && elem[0:l] == "token/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "deploy"

						if l := len("deploy"); len(elem) >= l && elem[0:l] == "deploy" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleTokenDeployRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn36AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'o': // Prefix: "oidc"

						if l := len("oidc"); len(elem) >= l && elem[0:l] == "oidc" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleTokenOIDCRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn38AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'r': // Prefix: "refresh"

						if l := len("refresh"); len(elem) >= l && elem[0:l] == "refresh" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleTokenRefreshRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn39AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'h': // Prefix: "healthz"

				if l := len("healthz"); len(elem) >= l && elem[0:l] == "healthz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetHealthzRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [4]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/"

				if l := len("api/"); len(elem) >= l && elem[0:l] == "api/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'o': // Prefix: "operator/"

					if l := len("operator/"); len(elem) >= l && elem[0:l] == "operator/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "approvals"

						if l := len("approvals"); len(elem) >= l && elem[0:l] == "approvals" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListOperatorApprovalsOperation
								r.summary = "List all pending approvals"
								r.operationID = "listOperatorApprovals"
								r.operationGroup = ""
								r.pathPattern = "/api/operator/approvals"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'b': // Prefix: "batch"
								origElem := elem
								if l := len("batch"); len(elem) >= l && elem[0:l] == "batch" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = BatchActionApprovalsOperation
										r.summary = "Approve or reject multiple approvals"
										r.operationID = "batchActionApprovals"
										r.operationGroup = ""
										r.pathPattern = "/api/operator/approvals/batch"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

								elem = origElem
							}
							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetOperatorApprovalOperation
									r.summary = "Get single approval detail"
									r.operationID = "getOperatorApproval"
									r.operationGroup = ""
									r.pathPattern = "/api/operator/approvals/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					case 'c': // Prefix: "co"

						if l := len("co"); len(elem) >= l && elem[0:l] == "co" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'n': // Prefix: "nfig"

							if l := len("nfig"); len(elem) >= l && elem[0:l] == "nfig" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetOperatorConfigOperation
									r.summary = "Read platform config"
									r.operationID = "getOperatorConfig"
									r.operationGroup = ""
									r.pathPattern = "/api/operator/config"
									r.args = args
									r.count = 0
									return r, true
								case "PATCH":
									r.name = UpdateOperatorConfigOperation
									r.summary = "Update mutable platform config"
									r.operationID = "updateOperatorConfig"
									r.operationGroup = ""
									r.pathPattern = "/api/operator/config"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "st"

							if l := len("st"); len(elem) >= l && elem[0:l] == "st" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetOperatorCostOperation
									r.summary = "Platform-wide cost estimate"
									r.operationID = "getOperatorCost"
									r.operationGroup = ""
									r.pathPattern = "/api/operator/cost"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'p': // Prefix: "principals"

						if l := len("principals"); len(elem) >= l && elem[0:l] == "principals" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListOperatorPrincipalsOperation
								r.summary = "List operator principals"
								r.operationID = "listOperatorPrincipals"
								r.operationGroup = ""
								r.pathPattern = "/api/operator/principals"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = AddOperatorPrincipalOperation
								r.summary = "Add an operator principal"
								r.operationID = "addOperatorPrincipal"
								r.operationGroup = ""
								r.pathPattern = "/api/operator/principals"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "principal"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = RemoveOperatorPrincipalOperation
									r.summary = "Remove an operator principal"
									r.operationID = "removeOperatorPrincipal"
									r.operationGroup = ""
									r.pathPattern = "/api/operator/principals/{principal}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					case 'r': // Prefix: "repos/"

						if l := len("repos/"); len(elem) >= l && elem[0:l] == "repos/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "org"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "repo"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[1] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PATCH":
									r.name = UpdateRepoTierOperation
									r.summary = "Promote or demote repo tier"
									r.operationID = "updateRepoTier"
									r.operationGroup = ""
									r.pathPattern = "/api/operator/repos/{org}/{repo}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}

						}

					case 's': // Prefix: "status"

						if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetOperatorStatusOperation
								r.summary = "Platform health summary"
								r.operationID = "getOperatorStatus"
								r.operationGroup = ""
								r.pathPattern = "/api/operator/status"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'r': // Prefix: "repos"

					if l := len("repos"); len(elem) >= l && elem[0:l] == "repos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ListReposOperation
							r.summary = "List repos"
							r.operationID = "listRepos"
							r.operationGroup = ""
							r.pathPattern = "/api/repos"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "org"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "repo"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[1] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = DeleteRepoOperation
									r.summary = "Delete all apps in a repo"
									r.operationID = "deleteRepo"
									r.operationGroup = ""
									r.pathPattern = "/api/repos/{org}/{repo}"
									r.args = args
									r.count = 2
									return r, true
								case "GET":
									r.name = GetRepoOperation
									r.summary = "Get repo detail including tier and quota"
									r.operationID = "getRepo"
									r.operationGroup = ""
									r.pathPattern = "/api/repos/{org}/{repo}"
									r.args = args
									r.count = 2
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "app"

									if l := len("app"); len(elem) >= l && elem[0:l] == "app" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'r': // Prefix: "rovals"

										if l := len("rovals"); len(elem) >= l && elem[0:l] == "rovals" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = ListRepoApprovalsOperation
												r.summary = "List pending approvals for a repo"
												r.operationID = "listRepoApprovals"
												r.operationGroup = ""
												r.pathPattern = "/api/repos/{org}/{repo}/approvals"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									case 's': // Prefix: "s"

										if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											switch method {
											case "GET":
												r.name = ListAppsOperation
												r.summary = "List apps in a repo"
												r.operationID = "listApps"
												r.operationGroup = ""
												r.pathPattern = "/api/repos/{org}/{repo}/apps"
												r.args = args
												r.count = 2
												return r, true
											case "POST":
												r.name = UpsertAppOperation
												r.summary = "Upsert an app; runs staging handshake and applies Kubernetes manifest"
												r.operationID = "upsertApp"
												r.operationGroup = ""
												r.pathPattern = "/api/repos/{org}/{repo}/apps"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "name"
											// Match until "/"
											idx := strings.IndexByte(elem, '/')
											if idx < 0 {
												idx = len(elem)
											}
											args[2] = elem[:idx]
											elem = elem[idx:]

											if len(elem) == 0 {
												switch method {
												case "DELETE":
													r.name = DeleteAppOperation
													r.summary = "Delete an app; starts persistence grace period"
													r.operationID = "deleteApp"
													r.operationGroup = ""
													r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}"
													r.args = args
													r.count = 3
													return r, true
												case "GET":
													r.name = GetAppOperation
													r.summary = "Get app detail"
													r.operationID = "getApp"
													r.operationGroup = ""
													r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}"
													r.args = args
													r.count = 3
													return r, true
												default:
													return
												}
											}
											switch elem[0] {
											case '/': // Prefix: "/"

												if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													break
												}
												switch elem[0] {
												case 'h': // Prefix: "hi"

													if l := len("hi"); len(elem) >= l && elem[0:l] == "hi" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														break
													}
													switch elem[0] {
													case 'b': // Prefix: "bernate"

														if l := len("bernate"); len(elem) >= l && elem[0:l] == "bernate" {
															elem = elem[l:]
														} else {
															break
														}

														if len(elem) == 0 {
															// Leaf node.
															switch method {
															case "POST":
																r.name = HibernateAppOperation
																r.summary = "Force hibernate an app"
																r.operationID = "hibernateApp"
																r.operationGroup = ""
																r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}/hibernate"
																r.args = args
																r.count = 3
																return r, true
															default:
																return
															}
														}

													case 's': // Prefix: "story"

														if l := len("story"); len(elem) >= l && elem[0:l] == "story" {
															elem = elem[l:]
														} else {
															break
														}

														if len(elem) == 0 {
															// Leaf node.
															switch method {
															case "GET":
																r.name = GetAppHistoryOperation
																r.summary = "Get deploy history for an app"
																r.operationID = "getAppHistory"
																r.operationGroup = ""
																r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}/history"
																r.args = args
																r.count = 3
																return r, true
															default:
																return
															}
														}

													}

												case 'o': // Prefix: "operations/"

													if l := len("operations/"); len(elem) >= l && elem[0:l] == "operations/" {
														elem = elem[l:]
													} else {
														break
													}

													// Param: "id"
													// Leaf parameter, slashes are prohibited
													idx := strings.IndexByte(elem, '/')
													if idx >= 0 {
														break
													}
													args[3] = elem
													elem = ""

													if len(elem) == 0 {
														// Leaf node.
														switch method {
														case "GET":
															r.name = GetOperationOperation
															r.summary = "Poll an async operation"
															r.operationID = "getOperation"
															r.operationGroup = ""
															r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}/operations/{id}"
															r.args = args
															r.count = 4
															return r, true
														default:
															return
														}
													}

												case 's': // Prefix: "status"

													if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch method {
														case "GET":
															r.name = GetAppStatusOperation
															r.summary = "Get current runtime state of an app"
															r.operationID = "getAppStatus"
															r.operationGroup = ""
															r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}/status"
															r.args = args
															r.count = 3
															return r, true
														default:
															return
														}
													}

												case 'u': // Prefix: "utilisation"

													if l := len("utilisation"); len(elem) >= l && elem[0:l] == "utilisation" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch method {
														case "GET":
															r.name = GetAppUtilisationOperation
															r.summary = "Get current resource usage and cost estimate for an app"
															r.operationID = "getAppUtilisation"
															r.operationGroup = ""
															r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}/utilisation"
															r.args = args
															r.count = 3
															return r, true
														default:
															return
														}
													}

												case 'w': // Prefix: "wake"

													if l := len("wake"); len(elem) >= l && elem[0:l] == "wake" {
														elem = elem[l:]
													} else {
														break
													}

													if len(elem) == 0 {
														// Leaf node.
														switch method {
														case "POST":
															r.name = WakeAppOperation
															r.summary = "Force wake a hibernated app"
															r.operationID = "wakeApp"
															r.operationGroup = ""
															r.pathPattern = "/api/repos/{org}/{repo}/apps/{name}/wake"
															r.args = args
															r.count = 3
															return r, true
														default:
															return
														}
													}

												}

											}

										}

									}

								case 's': // Prefix: "sync"

									if l := len("sync"); len(elem) >= l && elem[0:l] == "sync" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = SyncRepoOperation
											r.summary = "Declarative app list reconciliation; detects deleted apps"
											r.operationID = "syncRepo"
											r.operationGroup = ""
											r.pathPattern = "/api/repos/{org}/{repo}/sync"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							}

						}

					}

				case 't': // Prefix: "token/"

					if l := len("token/"); len(elem) >= l && elem[0:l] == "token/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'd': // Prefix: "deploy"

						if l := len("deploy"); len(elem) >= l && elem[0:l] == "deploy" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = TokenDeployOperation
								r.summary = "Exchange a deploy identity token for a developer access token"
								r.operationID = "tokenDeploy"
								r.operationGroup = ""
								r.pathPattern = "/api/token/deploy"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "oidc"

						if l := len("oidc"); len(elem) >= l && elem[0:l] == "oidc" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = TokenOIDCOperation
								r.summary = "Exchange a platform identity credential for an operator access token and refresh token"
								r.operationID = "tokenOIDC"
								r.operationGroup = ""
								r.pathPattern = "/api/token/oidc"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'r': // Prefix: "refresh"

						if l := len("refresh"); len(elem) >= l && elem[0:l] == "refresh" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = TokenRefreshOperation
								r.summary = "Exchange a refresh token for a new access token and rotated refresh token"
								r.operationID = "tokenRefresh"
								r.operationGroup = ""
								r.pathPattern = "/api/token/refresh"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'h': // Prefix: "healthz"

				if l := len("healthz"); len(elem) >= l && elem[0:l] == "healthz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetHealthzOperation
						r.summary = "Health check"
						r.operationID = "getHealthz"
						r.operationGroup = ""
						r.pathPattern = "/healthz"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
