// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package queries

import (
	"context"
	"database/sql"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (repo_slug, name, type, namespace)
VALUES (?, ?, ?, ?)
RETURNING id, repo_slug, name, type, status, namespace, image_current, image_last_healthy, permanent, deletion_pending, deleted_at, created_at, updated_at
`

type CreateAppParams struct {
	RepoSlug  string
	Name      string
	Type      string
	Namespace sql.NullString
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp,
		arg.RepoSlug,
		arg.Name,
		arg.Type,
		arg.Namespace,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.RepoSlug,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Namespace,
		&i.ImageCurrent,
		&i.ImageLastHealthy,
		&i.Permanent,
		&i.DeletionPending,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, repo_slug, name, type, status, namespace, image_current, image_last_healthy, permanent, deletion_pending, deleted_at, created_at, updated_at FROM apps
WHERE repo_slug = ? AND name = ?
`

type GetAppParams struct {
	RepoSlug string
	Name     string
}

func (q *Queries) GetApp(ctx context.Context, arg GetAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, arg.RepoSlug, arg.Name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.RepoSlug,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Namespace,
		&i.ImageCurrent,
		&i.ImageLastHealthy,
		&i.Permanent,
		&i.DeletionPending,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppsByRepo = `-- name: ListAppsByRepo :many
SELECT id, repo_slug, name, type, status, namespace, image_current, image_last_healthy, permanent, deletion_pending, deleted_at, created_at, updated_at FROM apps
WHERE repo_slug = ? AND deletion_pending = 0
ORDER BY name
`

func (q *Queries) ListAppsByRepo(ctx context.Context, repoSlug string) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByRepo, repoSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.RepoSlug,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Namespace,
			&i.ImageCurrent,
			&i.ImageLastHealthy,
			&i.Permanent,
			&i.DeletionPending,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppDeletionPending = `-- name: MarkAppDeletionPending :exec
UPDATE apps
SET deletion_pending = 1,
    deleted_at       = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at       = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

func (q *Queries) MarkAppDeletionPending(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markAppDeletionPending, id)
	return err
}

const updateAppImages = `-- name: UpdateAppImages :exec
UPDATE apps
SET image_current      = ?,
    image_last_healthy = ?,
    updated_at         = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateAppImagesParams struct {
	ImageCurrent     sql.NullString
	ImageLastHealthy sql.NullString
	ID               int64
}

func (q *Queries) UpdateAppImages(ctx context.Context, arg UpdateAppImagesParams) error {
	_, err := q.db.ExecContext(ctx, updateAppImages, arg.ImageCurrent, arg.ImageLastHealthy, arg.ID)
	return err
}

const updateAppStatus = `-- name: UpdateAppStatus :exec
UPDATE apps
SET status     = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateAppStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateAppStatus(ctx context.Context, arg UpdateAppStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAppStatus, arg.Status, arg.ID)
	return err
}
