// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, subject, role, repo_slug, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = ?
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.Role,
		&i.RepoSlug,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, token_hash, subject, role, repo_slug, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRefreshTokenParams struct {
	ID        string
	TokenHash string
	Subject   string
	Role      string
	RepoSlug  sql.NullString
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.Subject,
		arg.Role,
		arg.RepoSlug,
		arg.ExpiresAt,
	)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE refresh_tokens
SET token_hash = ?,
    expires_at = ?
WHERE id = ?
RETURNING id, token_hash, subject, role, repo_slug, expires_at, revoked_at, created_at
`

type RotateRefreshTokenParams struct {
	TokenHash string
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, rotateRefreshToken, arg.TokenHash, arg.ExpiresAt, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Subject,
		&i.Role,
		&i.RepoSlug,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
