// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package queries

import (
	"context"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (slug, tier)
VALUES (?, ?)
RETURNING slug, tier, created_at
`

type CreateRepoParams struct {
	Slug string
	Tier string
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, createRepo, arg.Slug, arg.Tier)
	var i Repo
	err := row.Scan(&i.Slug, &i.Tier, &i.CreatedAt)
	return i, err
}

const getRepo = `-- name: GetRepo :one
SELECT slug, tier, created_at FROM repos
WHERE slug = ?
`

func (q *Queries) GetRepo(ctx context.Context, slug string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepo, slug)
	var i Repo
	err := row.Scan(&i.Slug, &i.Tier, &i.CreatedAt)
	return i, err
}

const listRepos = `-- name: ListRepos :many
SELECT slug, tier, created_at FROM repos
ORDER BY slug
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(&i.Slug, &i.Tier, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoTier = `-- name: UpdateRepoTier :one
UPDATE repos
SET tier = ?
WHERE slug = ?
RETURNING slug, tier, created_at
`

type UpdateRepoTierParams struct {
	Tier string
	Slug string
}

func (q *Queries) UpdateRepoTier(ctx context.Context, arg UpdateRepoTierParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, updateRepoTier, arg.Tier, arg.Slug)
	var i Repo
	err := row.Scan(&i.Slug, &i.Tier, &i.CreatedAt)
	return i, err
}
