// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package queries

import (
	"context"
	"database/sql"
)

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const getMessageBodySize = `-- name: GetMessageBodySize :one
SELECT body_size FROM messages WHERE id = ?
`

func (q *Queries) GetMessageBodySize(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageBodySize, id)
	var body_size int64
	err := row.Scan(&body_size)
	return body_size, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages(id, body, body_size, enqueued_at) VALUES (?, ?, ?, ?)
`

type InsertMessageParams struct {
	ID         string
	Body       []byte
	BodySize   int64
	EnqueuedAt string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.Body,
		arg.BodySize,
		arg.EnqueuedAt,
	)
	return err
}

const selectNextMessage = `-- name: SelectNextMessage :one
SELECT id, body, enqueued_at FROM messages
WHERE visibility_until IS NULL
   OR visibility_until < strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
ORDER BY enqueued_at ASC LIMIT 1
`

type SelectNextMessageRow struct {
	ID         string
	Body       []byte
	EnqueuedAt string
}

func (q *Queries) SelectNextMessage(ctx context.Context) (SelectNextMessageRow, error) {
	row := q.db.QueryRowContext(ctx, selectNextMessage)
	var i SelectNextMessageRow
	err := row.Scan(&i.ID, &i.Body, &i.EnqueuedAt)
	return i, err
}

const setVisibility = `-- name: SetVisibility :exec
UPDATE messages SET visibility_until = ? WHERE id = ?
`

type SetVisibilityParams struct {
	VisibilityUntil sql.NullString
	ID              string
}

func (q *Queries) SetVisibility(ctx context.Context, arg SetVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, setVisibility, arg.VisibilityUntil, arg.ID)
	return err
}
