// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
)

type Message struct {
	ID              string
	Body            []byte
	BodySize        int64
	EnqueuedAt      string
	VisibilityUntil sql.NullString
}

type Meta struct {
	Key   string
	Value string
}

type Quotum struct {
	TotalBytes int64
	LimitBytes int64
}
