// Hand-written queries for stale-app suppression. Not generated by sqlc.
package queries

import (
	"context"
	"time"

	"github.com/ifeanyiecheruo/morsel/internal/ctxlog"
)

// StaleSuppressed represents one stale-app suppression entry.
type StaleSuppressed struct {
	RepoSlug string
	AppName  string
	Until    time.Time
}

// UpsertStaleSuppressed inserts or replaces a suppression for the given app.
func (q *Queries) UpsertStaleSuppressed(ctx context.Context, repoSlug, appName string, until time.Time) error {
	_, err := q.db.ExecContext(ctx, `
		INSERT INTO stale_suppressed (repo_slug, app_name, until)
		VALUES (?, ?, ?)
		ON CONFLICT (repo_slug, app_name) DO UPDATE SET until = excluded.until
	`, repoSlug, appName, until.Format(time.RFC3339))
	return err
}

// ListActiveStaleSuppressed returns all suppressions that have not yet expired.
func (q *Queries) ListActiveStaleSuppressed(ctx context.Context, now time.Time) ([]StaleSuppressed, error) {
	rows, err := q.db.QueryContext(ctx, `
		SELECT repo_slug, app_name, until
		FROM stale_suppressed
		WHERE until > ?
	`, now.Format(time.RFC3339))
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := rows.Close(); closeErr != nil {
			ctxlog.From(ctx).Warn("close rows", "err", closeErr)
		}
	}()

	var results []StaleSuppressed
	for rows.Next() {
		var s StaleSuppressed
		var untilStr string
		if err := rows.Scan(&s.RepoSlug, &s.AppName, &untilStr); err != nil {
			return nil, err
		}
		s.Until, _ = time.Parse(time.RFC3339, untilStr)
		results = append(results, s)
	}
	return results, rows.Err()
}
