// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exemptions.sql

package queries

import (
	"context"
	"database/sql"
)

const deleteAppExemption = `-- name: DeleteAppExemption :exec
DELETE FROM exemptions
WHERE kind = 'app' AND repo_slug = ? AND app_name = ? AND type = 'explicit'
`

type DeleteAppExemptionParams struct {
	RepoSlug string
	AppName  string
}

func (q *Queries) DeleteAppExemption(ctx context.Context, arg DeleteAppExemptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteAppExemption, arg.RepoSlug, arg.AppName)
	return err
}

const deleteRepoExemption = `-- name: DeleteRepoExemption :exec
DELETE FROM exemptions
WHERE kind = 'repo' AND repo_slug = ? AND type = 'explicit'
`

func (q *Queries) DeleteRepoExemption(ctx context.Context, repoSlug string) error {
	_, err := q.db.ExecContext(ctx, deleteRepoExemption, repoSlug)
	return err
}

const expirePeriodExemptions = `-- name: ExpirePeriodExemptions :exec
DELETE FROM exemptions
WHERE type = 'period' AND expires_at <= ?
`

func (q *Queries) ExpirePeriodExemptions(ctx context.Context, expiresAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, expirePeriodExemptions, expiresAt)
	return err
}

const isAppExempt = `-- name: IsAppExempt :one
SELECT EXISTS (
    SELECT 1 FROM exemptions
    WHERE repo_slug = ?
      AND (kind = 'repo' OR (kind = 'app' AND app_name = ?))
      AND (expires_at IS NULL OR expires_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) AS is_exempt
`

type IsAppExemptParams struct {
	RepoSlug string
	AppName  string
}

func (q *Queries) IsAppExempt(ctx context.Context, arg IsAppExemptParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAppExempt, arg.RepoSlug, arg.AppName)
	var is_exempt bool
	err := row.Scan(&is_exempt)
	return is_exempt, err
}

const listActiveExemptions = `-- name: ListActiveExemptions :many
SELECT id, kind, repo_slug, app_name, type, expires_at, created_at FROM exemptions
WHERE expires_at IS NULL OR expires_at > strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
ORDER BY kind, repo_slug, app_name
`

func (q *Queries) ListActiveExemptions(ctx context.Context) ([]Exemption, error) {
	rows, err := q.db.QueryContext(ctx, listActiveExemptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exemption{}
	for rows.Next() {
		var i Exemption
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RepoSlug,
			&i.AppName,
			&i.Type,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExemption = `-- name: UpsertExemption :exec
INSERT INTO exemptions (kind, repo_slug, app_name, type, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (kind, repo_slug, app_name, type) DO UPDATE
    SET expires_at = excluded.expires_at
`

type UpsertExemptionParams struct {
	Kind      string
	RepoSlug  string
	AppName   string
	Type      string
	ExpiresAt sql.NullTime
}

func (q *Queries) UpsertExemption(ctx context.Context, arg UpsertExemptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertExemption,
		arg.Kind,
		arg.RepoSlug,
		arg.AppName,
		arg.Type,
		arg.ExpiresAt,
	)
	return err
}
