// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type App struct {
	ID                int64
	RepoSlug          string
	Name              string
	Type              string
	Status            string
	Namespace         sql.NullString
	ImageCurrent      sql.NullString
	ImageLastHealthy  sql.NullString
	Permanent         int64
	DeletionPending   int64
	DeletedAt         sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Hibernated        int64
	HibernatedAt      sql.NullTime
	HibernationReason sql.NullString
	LastActiveAt      sql.NullTime
	IdleAfter         sql.NullString
}

type Operation struct {
	ID        string
	RepoSlug  string
	AppName   string
	Kind      string
	Status    string
	Error     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Principal struct {
	Username     string
	PasswordHash sql.NullString
	Salt         sql.NullString
	CreatedAt    time.Time
}

type RefreshToken struct {
	ID        string
	TokenHash string
	Subject   string
	Role      string
	RepoSlug  sql.NullString
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type Repo struct {
	Slug      string
	Tier      string
	CreatedAt time.Time
}

type Tier struct {
	Name           string
	MaxApps        int64
	CpuMilli       int64
	MemoryMb       int64
	BlobGb         int64
	DatabaseGb     int64
	QueueGb        int64
	HibernateAfter string
	IsDefault      int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
