// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package queries

import (
	"context"
	"database/sql"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (id, repo_slug, app_name, kind)
VALUES (?, ?, ?, ?)
RETURNING id, repo_slug, app_name, kind, status, error, created_at, updated_at
`

type CreateOperationParams struct {
	ID       string
	RepoSlug string
	AppName  string
	Kind     string
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRowContext(ctx, createOperation,
		arg.ID,
		arg.RepoSlug,
		arg.AppName,
		arg.Kind,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.RepoSlug,
		&i.AppName,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT id, repo_slug, app_name, kind, status, error, created_at, updated_at FROM operations
WHERE id = ?
`

func (q *Queries) GetOperation(ctx context.Context, id string) (Operation, error) {
	row := q.db.QueryRowContext(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.RepoSlug,
		&i.AppName,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperationsByApp = `-- name: ListOperationsByApp :many
SELECT id, repo_slug, app_name, kind, status, error, created_at, updated_at FROM operations
WHERE repo_slug = ? AND app_name = ?
ORDER BY created_at DESC
`

type ListOperationsByAppParams struct {
	RepoSlug string
	AppName  string
}

func (q *Queries) ListOperationsByApp(ctx context.Context, arg ListOperationsByAppParams) ([]Operation, error) {
	rows, err := q.db.QueryContext(ctx, listOperationsByApp, arg.RepoSlug, arg.AppName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.RepoSlug,
			&i.AppName,
			&i.Kind,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperationStatus = `-- name: UpdateOperationStatus :exec
UPDATE operations
SET status     = ?,
    error      = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateOperationStatusParams struct {
	Status string
	Error  sql.NullString
	ID     string
}

func (q *Queries) UpdateOperationStatus(ctx context.Context, arg UpdateOperationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOperationStatus, arg.Status, arg.Error, arg.ID)
	return err
}
