// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_config.sql

package queries

import (
	"context"
)

const getPlatformConfig = `-- name: GetPlatformConfig :one
SELECT id, budget_ceiling_monthly, soft_limit_pct, hard_limit_pct, default_idle_after, budget_soft_limit_active, budget_hard_limit_active, billing_period FROM platform_config WHERE id = 1
`

func (q *Queries) GetPlatformConfig(ctx context.Context) (PlatformConfig, error) {
	row := q.db.QueryRowContext(ctx, getPlatformConfig)
	var i PlatformConfig
	err := row.Scan(
		&i.ID,
		&i.BudgetCeilingMonthly,
		&i.SoftLimitPct,
		&i.HardLimitPct,
		&i.DefaultIdleAfter,
		&i.BudgetSoftLimitActive,
		&i.BudgetHardLimitActive,
		&i.BillingPeriod,
	)
	return i, err
}

const updatePlatformConfig = `-- name: UpdatePlatformConfig :one
UPDATE platform_config
SET budget_ceiling_monthly   = ?,
    soft_limit_pct           = ?,
    hard_limit_pct           = ?,
    default_idle_after       = ?,
    budget_soft_limit_active = ?,
    budget_hard_limit_active = ?,
    billing_period           = ?
WHERE id = 1
RETURNING id, budget_ceiling_monthly, soft_limit_pct, hard_limit_pct, default_idle_after, budget_soft_limit_active, budget_hard_limit_active, billing_period
`

type UpdatePlatformConfigParams struct {
	BudgetCeilingMonthly  float64
	SoftLimitPct          float64
	HardLimitPct          float64
	DefaultIdleAfter      string
	BudgetSoftLimitActive int64
	BudgetHardLimitActive int64
	BillingPeriod         string
}

func (q *Queries) UpdatePlatformConfig(ctx context.Context, arg UpdatePlatformConfigParams) (PlatformConfig, error) {
	row := q.db.QueryRowContext(ctx, updatePlatformConfig,
		arg.BudgetCeilingMonthly,
		arg.SoftLimitPct,
		arg.HardLimitPct,
		arg.DefaultIdleAfter,
		arg.BudgetSoftLimitActive,
		arg.BudgetHardLimitActive,
		arg.BillingPeriod,
	)
	var i PlatformConfig
	err := row.Scan(
		&i.ID,
		&i.BudgetCeilingMonthly,
		&i.SoftLimitPct,
		&i.HardLimitPct,
		&i.DefaultIdleAfter,
		&i.BudgetSoftLimitActive,
		&i.BudgetHardLimitActive,
		&i.BillingPeriod,
	)
	return i, err
}
