// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_snapshots.sql

package queries

import (
	"context"
	"time"
)

const getLatestPriceSnapshot = `-- name: GetLatestPriceSnapshot :one
SELECT id, compute_cpu_per_core_hour, compute_mem_per_gb_hour, storage_per_gb_month, registry_per_gb_month, fetched_at FROM price_snapshots
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPriceSnapshot(ctx context.Context) (PriceSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestPriceSnapshot)
	var i PriceSnapshot
	err := row.Scan(
		&i.ID,
		&i.ComputeCpuPerCoreHour,
		&i.ComputeMemPerGbHour,
		&i.StoragePerGbMonth,
		&i.RegistryPerGbMonth,
		&i.FetchedAt,
	)
	return i, err
}

const insertPriceSnapshot = `-- name: InsertPriceSnapshot :one
INSERT INTO price_snapshots (compute_cpu_per_core_hour, compute_mem_per_gb_hour, storage_per_gb_month, registry_per_gb_month, fetched_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, compute_cpu_per_core_hour, compute_mem_per_gb_hour, storage_per_gb_month, registry_per_gb_month, fetched_at
`

type InsertPriceSnapshotParams struct {
	ComputeCpuPerCoreHour float64
	ComputeMemPerGbHour   float64
	StoragePerGbMonth     float64
	RegistryPerGbMonth    float64
	FetchedAt             time.Time
}

func (q *Queries) InsertPriceSnapshot(ctx context.Context, arg InsertPriceSnapshotParams) (PriceSnapshot, error) {
	row := q.db.QueryRowContext(ctx, insertPriceSnapshot,
		arg.ComputeCpuPerCoreHour,
		arg.ComputeMemPerGbHour,
		arg.StoragePerGbMonth,
		arg.RegistryPerGbMonth,
		arg.FetchedAt,
	)
	var i PriceSnapshot
	err := row.Scan(
		&i.ID,
		&i.ComputeCpuPerCoreHour,
		&i.ComputeMemPerGbHour,
		&i.StoragePerGbMonth,
		&i.RegistryPerGbMonth,
		&i.FetchedAt,
	)
	return i, err
}

const listPriceSnapshots = `-- name: ListPriceSnapshots :many
SELECT id, compute_cpu_per_core_hour, compute_mem_per_gb_hour, storage_per_gb_month, registry_per_gb_month, fetched_at FROM price_snapshots
ORDER BY fetched_at DESC
`

func (q *Queries) ListPriceSnapshots(ctx context.Context) ([]PriceSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listPriceSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceSnapshot{}
	for rows.Next() {
		var i PriceSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ComputeCpuPerCoreHour,
			&i.ComputeMemPerGbHour,
			&i.StoragePerGbMonth,
			&i.RegistryPerGbMonth,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
