// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package queries

import (
	"context"
	"database/sql"
)

const deletePrincipal = `-- name: DeletePrincipal :exec
DELETE FROM principals WHERE username = ?1
`

func (q *Queries) DeletePrincipal(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deletePrincipal, username)
	return err
}

const getPrincipalPasswordHash = `-- name: GetPrincipalPasswordHash :one
SELECT password_hash FROM principals WHERE username = ?1
`

func (q *Queries) GetPrincipalPasswordHash(ctx context.Context, username string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalPasswordHash, username)
	var password_hash sql.NullString
	err := row.Scan(&password_hash)
	return password_hash, err
}

const insertPrincipal = `-- name: InsertPrincipal :exec
INSERT INTO principals (username) VALUES (?1)
ON CONFLICT (username) DO NOTHING
`

func (q *Queries) InsertPrincipal(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, insertPrincipal, username)
	return err
}

const listPrincipals = `-- name: ListPrincipals :many
SELECT username FROM principals ORDER BY username
`

func (q *Queries) ListPrincipals(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const principalExists = `-- name: PrincipalExists :one
SELECT EXISTS(SELECT 1 FROM principals WHERE username = ?1) AS "exists"
`

func (q *Queries) PrincipalExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, principalExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setPrincipalPasswordHash = `-- name: SetPrincipalPasswordHash :exec
UPDATE principals SET password_hash = ?1 WHERE username = ?2
`

type SetPrincipalPasswordHashParams struct {
	PasswordHash sql.NullString
	Username     string
}

func (q *Queries) SetPrincipalPasswordHash(ctx context.Context, arg SetPrincipalPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, setPrincipalPasswordHash, arg.PasswordHash, arg.Username)
	return err
}
