// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package queries

import (
	"context"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM principals WHERE is_admin = 1
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOperators = `-- name: CountOperators :one
SELECT COUNT(*) FROM principals WHERE is_operator = 1
`

func (q *Queries) CountOperators(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePrincipal = `-- name: DeletePrincipal :exec
DELETE FROM principals WHERE github_id = ?1
`

func (q *Queries) DeletePrincipal(ctx context.Context, githubID int64) error {
	_, err := q.db.ExecContext(ctx, deletePrincipal, githubID)
	return err
}

const getPrincipalByID = `-- name: GetPrincipalByID :one
SELECT github_id, github_login, is_operator, is_admin, created_at FROM principals WHERE github_id = ?1
`

func (q *Queries) GetPrincipalByID(ctx context.Context, githubID int64) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByID, githubID)
	var i Principal
	err := row.Scan(
		&i.GithubID,
		&i.GithubLogin,
		&i.IsOperator,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getPrincipalByLogin = `-- name: GetPrincipalByLogin :one
SELECT github_id, github_login, is_operator, is_admin, created_at FROM principals WHERE github_login = ?1
`

func (q *Queries) GetPrincipalByLogin(ctx context.Context, githubLogin string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByLogin, githubLogin)
	var i Principal
	err := row.Scan(
		&i.GithubID,
		&i.GithubLogin,
		&i.IsOperator,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listPrincipals = `-- name: ListPrincipals :many
SELECT github_id, github_login, is_operator, is_admin, created_at FROM principals ORDER BY github_login
`

func (q *Queries) ListPrincipals(ctx context.Context) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.GithubID,
			&i.GithubLogin,
			&i.IsOperator,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrincipalIsAdmin = `-- name: SetPrincipalIsAdmin :exec
UPDATE principals SET is_admin = ?1 WHERE github_id = ?2
`

type SetPrincipalIsAdminParams struct {
	IsAdmin  int64
	GithubID int64
}

func (q *Queries) SetPrincipalIsAdmin(ctx context.Context, arg SetPrincipalIsAdminParams) error {
	_, err := q.db.ExecContext(ctx, setPrincipalIsAdmin, arg.IsAdmin, arg.GithubID)
	return err
}

const setPrincipalIsOperator = `-- name: SetPrincipalIsOperator :exec
UPDATE principals SET is_operator = ?1 WHERE github_id = ?2
`

type SetPrincipalIsOperatorParams struct {
	IsOperator int64
	GithubID   int64
}

func (q *Queries) SetPrincipalIsOperator(ctx context.Context, arg SetPrincipalIsOperatorParams) error {
	_, err := q.db.ExecContext(ctx, setPrincipalIsOperator, arg.IsOperator, arg.GithubID)
	return err
}

const upsertPrincipal = `-- name: UpsertPrincipal :one
INSERT INTO principals (github_id, github_login)
VALUES (?1, ?2)
ON CONFLICT (github_id) DO UPDATE SET github_login = excluded.github_login
RETURNING github_id, github_login, is_operator, is_admin, created_at
`

type UpsertPrincipalParams struct {
	GithubID    int64
	GithubLogin string
}

func (q *Queries) UpsertPrincipal(ctx context.Context, arg UpsertPrincipalParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, upsertPrincipal, arg.GithubID, arg.GithubLogin)
	var i Principal
	err := row.Scan(
		&i.GithubID,
		&i.GithubLogin,
		&i.IsOperator,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
