// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scale_events.sql

package queries

import (
	"context"
	"time"
)

const insertScaleEvent = `-- name: InsertScaleEvent :exec
INSERT INTO scale_events (namespace, app, event, occurred_at)
VALUES (?, ?, ?, ?)
`

type InsertScaleEventParams struct {
	Namespace  string
	App        string
	Event      string
	OccurredAt time.Time
}

func (q *Queries) InsertScaleEvent(ctx context.Context, arg InsertScaleEventParams) error {
	_, err := q.db.ExecContext(ctx, insertScaleEvent,
		arg.Namespace,
		arg.App,
		arg.Event,
		arg.OccurredAt,
	)
	return err
}

const listAllScaleEventsSince = `-- name: ListAllScaleEventsSince :many
SELECT id, namespace, app, event, occurred_at FROM scale_events
WHERE occurred_at >= ?
ORDER BY namespace, app, occurred_at
`

func (q *Queries) ListAllScaleEventsSince(ctx context.Context, occurredAt time.Time) ([]ScaleEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAllScaleEventsSince, occurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScaleEvent{}
	for rows.Next() {
		var i ScaleEvent
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.App,
			&i.Event,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScaleEventsSince = `-- name: ListScaleEventsSince :many
SELECT id, namespace, app, event, occurred_at FROM scale_events
WHERE namespace = ? AND app = ? AND occurred_at >= ?
ORDER BY occurred_at
`

type ListScaleEventsSinceParams struct {
	Namespace  string
	App        string
	OccurredAt time.Time
}

func (q *Queries) ListScaleEventsSince(ctx context.Context, arg ListScaleEventsSinceParams) ([]ScaleEvent, error) {
	rows, err := q.db.QueryContext(ctx, listScaleEventsSince, arg.Namespace, arg.App, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScaleEvent{}
	for rows.Next() {
		var i ScaleEvent
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.App,
			&i.Event,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
