// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stale_suppressed.sql

package queries

import (
	"context"
)

const listActiveStaleSuppressed = `-- name: ListActiveStaleSuppressed :many
SELECT repo_slug, app_name, until
FROM stale_suppressed
WHERE until > ?
`

func (q *Queries) ListActiveStaleSuppressed(ctx context.Context, until string) ([]StaleSuppressed, error) {
	rows, err := q.db.QueryContext(ctx, listActiveStaleSuppressed, until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaleSuppressed{}
	for rows.Next() {
		var i StaleSuppressed
		if err := rows.Scan(&i.RepoSlug, &i.AppName, &i.Until); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStaleSuppressed = `-- name: UpsertStaleSuppressed :exec
INSERT INTO stale_suppressed (repo_slug, app_name, until)
VALUES (?, ?, ?)
ON CONFLICT (repo_slug, app_name) DO UPDATE SET until = excluded.until
`

type UpsertStaleSuppressedParams struct {
	RepoSlug string
	AppName  string
	Until    string
}

func (q *Queries) UpsertStaleSuppressed(ctx context.Context, arg UpsertStaleSuppressedParams) error {
	_, err := q.db.ExecContext(ctx, upsertStaleSuppressed, arg.RepoSlug, arg.AppName, arg.Until)
	return err
}
