// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *SetPrincipalPasswordReq) setDefaults() {
	{
		val := bool(false)
		s.Invalidate.SetTo(val)
	}
}
