// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AddOperatorPrincipalOperation     OperationName = "AddOperatorPrincipal"
	BatchActionApprovalsOperation     OperationName = "BatchActionApprovals"
	CreateTierOperation               OperationName = "CreateTier"
	DeleteAppOperation                OperationName = "DeleteApp"
	DeleteRepoOperation               OperationName = "DeleteRepo"
	DeleteTierOperation               OperationName = "DeleteTier"
	GetAppOperation                   OperationName = "GetApp"
	GetAppHistoryOperation            OperationName = "GetAppHistory"
	GetAppStatusOperation             OperationName = "GetAppStatus"
	GetAppUtilisationOperation        OperationName = "GetAppUtilisation"
	GetDeploymentInfoOperation        OperationName = "GetDeploymentInfo"
	GetHealthzOperation               OperationName = "GetHealthz"
	GetOperationOperation             OperationName = "GetOperation"
	GetOperatorApprovalOperation      OperationName = "GetOperatorApproval"
	GetOperatorConfigOperation        OperationName = "GetOperatorConfig"
	GetOperatorCostOperation          OperationName = "GetOperatorCost"
	GetOperatorPricesHistoryOperation OperationName = "GetOperatorPricesHistory"
	GetOperatorStatusOperation        OperationName = "GetOperatorStatus"
	GetRepoOperation                  OperationName = "GetRepo"
	HibernateAppOperation             OperationName = "HibernateApp"
	ListAppsOperation                 OperationName = "ListApps"
	ListOperatorApprovalsOperation    OperationName = "ListOperatorApprovals"
	ListOperatorPrincipalsOperation   OperationName = "ListOperatorPrincipals"
	ListRepoApprovalsOperation        OperationName = "ListRepoApprovals"
	ListReposOperation                OperationName = "ListRepos"
	ListTiersOperation                OperationName = "ListTiers"
	PrepareRepoDeployOperation        OperationName = "PrepareRepoDeploy"
	RemoveOperatorPrincipalOperation  OperationName = "RemoveOperatorPrincipal"
	SetDefaultTierOperation           OperationName = "SetDefaultTier"
	SyncRepoOperation                 OperationName = "SyncRepo"
	TokenDeployOperation              OperationName = "TokenDeploy"
	TokenOIDCOperation                OperationName = "TokenOIDC"
	TokenRefreshOperation             OperationName = "TokenRefresh"
	UpdateOperatorConfigOperation     OperationName = "UpdateOperatorConfig"
	UpdateRepoTierOperation           OperationName = "UpdateRepoTier"
	UpdateTierOperation               OperationName = "UpdateTier"
	UpsertAppOperation                OperationName = "UpsertApp"
	WakeAppOperation                  OperationName = "WakeApp"
)
