// Code generated by ogen, DO NOT EDIT.

package oas

// DeleteAppParams is parameters of deleteApp operation.
type DeleteAppParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}

// DeleteRepoParams is parameters of deleteRepo operation.
type DeleteRepoParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// DeleteTierParams is parameters of deleteTier operation.
type DeleteTierParams struct {
	// The tier name.
	Name string
}

// GetAppParams is parameters of getApp operation.
type GetAppParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}

// GetAppHistoryParams is parameters of getAppHistory operation.
type GetAppHistoryParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}

// GetAppStatusParams is parameters of getAppStatus operation.
type GetAppStatusParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}

// GetAppUtilisationParams is parameters of getAppUtilisation operation.
type GetAppUtilisationParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}

// GetOperationParams is parameters of getOperation operation.
type GetOperationParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
	// The operation ID returned by a prior async request.
	ID string
}

// GetOperatorApprovalParams is parameters of getOperatorApproval operation.
type GetOperatorApprovalParams struct {
	// The approval request ID.
	ID string
}

// GetRepoParams is parameters of getRepo operation.
type GetRepoParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// HibernateAppParams is parameters of hibernateApp operation.
type HibernateAppParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}

// InvalidateOperatorPrincipalPasswordParams is parameters of invalidateOperatorPrincipalPassword operation.
type InvalidateOperatorPrincipalPasswordParams struct {
	// The principal identity (URL-encoded email address).
	Principal string
}

// ListAppsParams is parameters of listApps operation.
type ListAppsParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// ListRepoApprovalsParams is parameters of listRepoApprovals operation.
type ListRepoApprovalsParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// ListReposParams is parameters of listRepos operation.
type ListReposParams struct {
	// When true, returns all repos across all organisations. Requires operator privileges.
	All OptBool `json:",omitempty,omitzero"`
}

// PrepareRepoDeployParams is parameters of prepareRepoDeploy operation.
type PrepareRepoDeployParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// RemoveAppExemptionParams is parameters of removeAppExemption operation.
type RemoveAppExemptionParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}

// RemoveOperatorPrincipalParams is parameters of removeOperatorPrincipal operation.
type RemoveOperatorPrincipalParams struct {
	// The principal identity (URL-encoded email address) to remove.
	Principal string
}

// RemoveRepoExemptionParams is parameters of removeRepoExemption operation.
type RemoveRepoExemptionParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// RequirePasswordResetForPrincipalParams is parameters of requirePasswordResetForPrincipal operation.
type RequirePasswordResetForPrincipalParams struct {
	// The principal identity (URL-encoded email address) to flag.
	Principal string
}

// SetDefaultTierParams is parameters of setDefaultTier operation.
type SetDefaultTierParams struct {
	// The tier name.
	Name string
}

// SetOperatorPrincipalPasswordParams is parameters of setOperatorPrincipalPassword operation.
type SetOperatorPrincipalPasswordParams struct {
	// The principal identity (URL-encoded email address).
	Principal string
}

// SyncRepoParams is parameters of syncRepo operation.
type SyncRepoParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// UpdateRepoTierParams is parameters of updateRepoTier operation.
type UpdateRepoTierParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// UpdateTierParams is parameters of updateTier operation.
type UpdateTierParams struct {
	// The tier name.
	Name string
}

// UpsertAppParams is parameters of upsertApp operation.
type UpsertAppParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
}

// WakeAppParams is parameters of wakeApp operation.
type WakeAppParams struct {
	// The organisation or user that owns the repo.
	Org string
	// The repository name within the organisation.
	Repo string
	// The app name within the repo.
	Name string
}
