// Code generated by ogen, DO NOT EDIT.
package server

type AddAppExemptionRes interface {
	addAppExemptionRes()
}

type AddOperatorPrincipalRes interface {
	addOperatorPrincipalRes()
}

type AddRepoExemptionRes interface {
	addRepoExemptionRes()
}

type BatchActionApprovalsRes interface {
	batchActionApprovalsRes()
}

type CreateTierRes interface {
	createTierRes()
}

type DeleteAppRes interface {
	deleteAppRes()
}

type DeleteRepoRes interface {
	deleteRepoRes()
}

type DeleteTierRes interface {
	deleteTierRes()
}

type GetAppHistoryRes interface {
	getAppHistoryRes()
}

type GetAppRes interface {
	getAppRes()
}

type GetAppStatusRes interface {
	getAppStatusRes()
}

type GetAppUtilisationRes interface {
	getAppUtilisationRes()
}

type GetDeploymentInfoRes interface {
	getDeploymentInfoRes()
}

type GetHealthzRes interface {
	getHealthzRes()
}

type GetOperationRes interface {
	getOperationRes()
}

type GetOperatorApprovalRes interface {
	getOperatorApprovalRes()
}

type GetOperatorConfigRes interface {
	getOperatorConfigRes()
}

type GetOperatorCostRes interface {
	getOperatorCostRes()
}

type GetOperatorPricesHistoryRes interface {
	getOperatorPricesHistoryRes()
}

type GetOperatorStatusRes interface {
	getOperatorStatusRes()
}

type GetRepoRes interface {
	getRepoRes()
}

type HibernateAppRes interface {
	hibernateAppRes()
}

type InvalidateOperatorPrincipalPasswordRes interface {
	invalidateOperatorPrincipalPasswordRes()
}

type ListAppsRes interface {
	listAppsRes()
}

type ListExemptionsRes interface {
	listExemptionsRes()
}

type ListOperatorApprovalsRes interface {
	listOperatorApprovalsRes()
}

type ListOperatorPrincipalsRes interface {
	listOperatorPrincipalsRes()
}

type ListRepoApprovalsRes interface {
	listRepoApprovalsRes()
}

type ListReposRes interface {
	listReposRes()
}

type ListTiersRes interface {
	listTiersRes()
}

type PrepareRepoDeployRes interface {
	prepareRepoDeployRes()
}

type RemoveAppExemptionRes interface {
	removeAppExemptionRes()
}

type RemoveOperatorPrincipalRes interface {
	removeOperatorPrincipalRes()
}

type RemoveRepoExemptionRes interface {
	removeRepoExemptionRes()
}

type RequirePasswordResetForPrincipalRes interface {
	requirePasswordResetForPrincipalRes()
}

type ResetOperatorPasswordRes interface {
	resetOperatorPasswordRes()
}

type SetDefaultTierRes interface {
	setDefaultTierRes()
}

type SetOperatorPrincipalPasswordRes interface {
	setOperatorPrincipalPasswordRes()
}

type SyncRepoRes interface {
	syncRepoRes()
}

type TokenDeployRes interface {
	tokenDeployRes()
}

type TokenOIDCRes interface {
	tokenOIDCRes()
}

type TokenRefreshRes interface {
	tokenRefreshRes()
}

type UpdateOperatorConfigRes interface {
	updateOperatorConfigRes()
}

type UpdateRepoTierRes interface {
	updateRepoTierRes()
}

type UpdateTierRes interface {
	updateTierRes()
}

type UpsertAppRes interface {
	upsertAppRes()
}

type WakeAppRes interface {
	wakeAppRes()
}
