// Code generated by ogen, DO NOT EDIT.

package server

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddAppExemption implements addAppExemption operation.
	//
	// Permanently exempts a specific app from budget enforcement. The app continues to wake and run
	// normally even when the platform soft or hard limit is active.
	//
	// POST /api/operator/app-exemptions
	AddAppExemption(ctx context.Context, req *AppExemptionReq) (AddAppExemptionRes, error)
	// AddOperatorPrincipal implements addOperatorPrincipal operation.
	//
	// Grants admin UI access to the specified principal. Idempotent.
	//
	// POST /api/operator/principals
	AddOperatorPrincipal(ctx context.Context, req *PrincipalReq) (AddOperatorPrincipalRes, error)
	// AddRepoExemption implements addRepoExemption operation.
	//
	// Permanently exempts all apps in a repository from budget enforcement. Apps in the repo continue to
	// wake and run normally even when the platform soft or hard limit is active.
	//
	// POST /api/operator/repo-exemptions
	AddRepoExemption(ctx context.Context, req *RepoExemptionReq) (AddRepoExemptionRes, error)
	// BatchActionApprovals implements batchActionApprovals operation.
	//
	// Acts on multiple approval requests in one call. Approved changes are applied immediately; rejected
	// changes are discarded. IDs not found or already resolved appear in the ignored list.
	//
	// POST /api/operator/approvals/batch
	BatchActionApprovals(ctx context.Context, req *BatchActionApprovalsReq) (BatchActionApprovalsRes, error)
	// CreateTier implements createTier operation.
	//
	// Create a new quota tier.
	//
	// POST /api/operator/tiers
	CreateTier(ctx context.Context, req *CreateTierReq) (CreateTierRes, error)
	// DeleteApp implements deleteApp operation.
	//
	// Marks the app for deletion and begins a grace period before its persistent storage is removed. Poll
	// the returned operation to track progress.
	//
	// DELETE /api/repos/{org}/{repo}/apps/{name}
	DeleteApp(ctx context.Context, params DeleteAppParams) (DeleteAppRes, error)
	// DeleteRepo implements deleteRepo operation.
	//
	// Queues deletion of every app in the repo. Returns immediately; poll the returned operation to track
	// progress. The repo record is removed once all apps are gone.
	//
	// DELETE /api/repos/{org}/{repo}
	DeleteRepo(ctx context.Context, params DeleteRepoParams) (DeleteRepoRes, error)
	// DeleteTier implements deleteTier operation.
	//
	// Deletes the tier. Rejected if any repo is assigned to it or it is the platform default.
	//
	// DELETE /api/operator/tiers/{name}
	DeleteTier(ctx context.Context, params DeleteTierParams) (DeleteTierRes, error)
	// GetApp implements getApp operation.
	//
	// Returns the app's current configuration, status, and deployment timestamps.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}
	GetApp(ctx context.Context, params GetAppParams) (GetAppRes, error)
	// GetAppHistory implements getAppHistory operation.
	//
	// Returns past operations for the app in reverse chronological order, including deploys, deletes, and
	// hibernation events.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/history
	GetAppHistory(ctx context.Context, params GetAppHistoryParams) (GetAppHistoryRes, error)
	// GetAppStatus implements getAppStatus operation.
	//
	// Returns the Kubernetes-level status of the app including replica counts. Use this to determine
	// whether the app is healthy or still starting up.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/status
	GetAppStatus(ctx context.Context, params GetAppStatusParams) (GetAppStatusRes, error)
	// GetAppUtilisation implements getAppUtilisation operation.
	//
	// Returns recent CPU and memory usage averaged over the last collection window, and a projected
	// monthly cost at the current usage rate.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/utilisation
	GetAppUtilisation(ctx context.Context, params GetAppUtilisationParams) (GetAppUtilisationRes, error)
	// GetDeploymentInfo implements getDeploymentInfo operation.
	//
	// Returns parameters fixed at bootstrap time for the lifetime of this deployment.
	//
	// GET /api/operator/deployment
	GetDeploymentInfo(ctx context.Context) (GetDeploymentInfoRes, error)
	// GetHealthz implements getHealthz operation.
	//
	// Returns 200 when the API server is up and able to handle requests. Does not check downstream
	// dependencies.
	//
	// GET /healthz
	GetHealthz(ctx context.Context) (*GetHealthzOK, error)
	// GetOperation implements getOperation operation.
	//
	// Fetch the current state of a long-running operation. Retry until status is "complete" or "failed".
	// The Retry-After header on the originating 202 response suggests a polling interval.
	//
	// GET /api/repos/{org}/{repo}/apps/{name}/operations/{id}
	GetOperation(ctx context.Context, params GetOperationParams) (GetOperationRes, error)
	// GetOperatorApproval implements getOperatorApproval operation.
	//
	// Returns the full detail of a single approval request, including the current and requested field
	// values.
	//
	// GET /api/operator/approvals/{id}
	GetOperatorApproval(ctx context.Context, params GetOperatorApprovalParams) (GetOperatorApprovalRes, error)
	// GetOperatorConfig implements getOperatorConfig operation.
	//
	// Returns the current mutable platform-wide settings, including budget limits.
	//
	// GET /api/operator/config
	GetOperatorConfig(ctx context.Context) (GetOperatorConfigRes, error)
	// GetOperatorCost implements getOperatorCost operation.
	//
	// Returns the projected monthly spend across the entire platform, broken down by repo. Figures are
	// estimates based on current resource usage and tier pricing.
	//
	// GET /api/operator/cost
	GetOperatorCost(ctx context.Context) (GetOperatorCostRes, error)
	// GetOperatorPricesHistory implements getOperatorPricesHistory operation.
	//
	// Returns all stored platform price snapshots in reverse chronological order, for debugging cost
	// estimate changes.
	//
	// GET /api/operator/prices/history
	GetOperatorPricesHistory(ctx context.Context) (GetOperatorPricesHistoryRes, error)
	// GetOperatorStatus implements getOperatorStatus operation.
	//
	// Returns a high-level health snapshot of the platform, including whether critical components are
	// operational and how many apps are currently running.
	//
	// GET /api/operator/status
	GetOperatorStatus(ctx context.Context) (GetOperatorStatusRes, error)
	// GetRepo implements getRepo operation.
	//
	// Returns the repo's tier, app count, and registration timestamp.
	//
	// GET /api/repos/{org}/{repo}
	GetRepo(ctx context.Context, params GetRepoParams) (GetRepoRes, error)
	// HibernateApp implements hibernateApp operation.
	//
	// Scales the app to zero replicas immediately, freeing its compute resources. The app resumes
	// automatically on the next inbound request, or can be woken explicitly via the wake endpoint.
	//
	// POST /api/repos/{org}/{repo}/apps/{name}/hibernate
	HibernateApp(ctx context.Context, params HibernateAppParams) (HibernateAppRes, error)
	// InvalidateOperatorPrincipalPassword implements invalidateOperatorPrincipalPassword operation.
	//
	// Admin-only. Marks the specified principal as requiring a password reset and immediately invalidates
	// all existing refresh tokens. The password hash is preserved so the principal can still perform a
	// self-service reset using their old password via POST /api/operator/password.
	//
	// POST /api/operator/principals/{principal}/invalidate-password
	InvalidateOperatorPrincipalPassword(ctx context.Context, params InvalidateOperatorPrincipalPasswordParams) (InvalidateOperatorPrincipalPasswordRes, error)
	// ListApps implements listApps operation.
	//
	// Returns every app currently deployed in the repo, including their status and image.
	//
	// GET /api/repos/{org}/{repo}/apps
	ListApps(ctx context.Context, params ListAppsParams) (ListAppsRes, error)
	// ListExemptions implements listExemptions operation.
	//
	// Returns all active explicit and period exemptions. Period exemptions expire automatically at the end
	// of each billing period.
	//
	// GET /api/operator/exemptions
	ListExemptions(ctx context.Context) (ListExemptionsRes, error)
	// ListOperatorApprovals implements listOperatorApprovals operation.
	//
	// Returns every approval request across all repos that is waiting for operator action.
	//
	// GET /api/operator/approvals
	ListOperatorApprovals(ctx context.Context) (ListOperatorApprovalsRes, error)
	// ListOperatorPrincipals implements listOperatorPrincipals operation.
	//
	// Returns all principals authorised to access the operator UI.
	//
	// GET /api/operator/principals
	ListOperatorPrincipals(ctx context.Context) (ListOperatorPrincipalsRes, error)
	// ListRepoApprovals implements listRepoApprovals operation.
	//
	// Returns approval requests raised by changes to this repo that are awaiting operator action before
	// they take effect.
	//
	// GET /api/repos/{org}/{repo}/approvals
	ListRepoApprovals(ctx context.Context, params ListRepoApprovalsParams) (ListRepoApprovalsRes, error)
	// ListRepos implements listRepos operation.
	//
	// Returns repos the caller has access to. Developers see only their own repo; operators see all repos
	// by default.
	//
	// GET /api/repos
	ListRepos(ctx context.Context, params ListReposParams) (ListReposRes, error)
	// ListTiers implements listTiers operation.
	//
	// List all quota tiers.
	//
	// GET /api/operator/tiers
	ListTiers(ctx context.Context) (ListTiersRes, error)
	// PrepareRepoDeploy implements prepareRepoDeploy operation.
	//
	// Issues a short-lived deploy token scoped to this repository and returns the registry URL and
	// credentials needed to push images. All information required to build, push, and deploy is returned
	// in a single call.
	//
	// POST /api/repos/{org}/{repo}/deploy
	PrepareRepoDeploy(ctx context.Context, params PrepareRepoDeployParams) (PrepareRepoDeployRes, error)
	// RemoveAppExemption implements removeAppExemption operation.
	//
	// Removes the explicit budget exemption for a specific app. The app will again be subject to soft and
	// hard limit enforcement.
	//
	// DELETE /api/operator/app-exemptions/{org}/{repo}/{name}
	RemoveAppExemption(ctx context.Context, params RemoveAppExemptionParams) (RemoveAppExemptionRes, error)
	// RemoveOperatorPrincipal implements removeOperatorPrincipal operation.
	//
	// Revokes admin UI access from the specified principal.
	//
	// DELETE /api/operator/principals/{principal}
	RemoveOperatorPrincipal(ctx context.Context, params RemoveOperatorPrincipalParams) (RemoveOperatorPrincipalRes, error)
	// RemoveRepoExemption implements removeRepoExemption operation.
	//
	// Removes the explicit budget exemption for a repository. All apps in the repo will again be subject
	// to soft and hard limit enforcement.
	//
	// DELETE /api/operator/repo-exemptions/{org}/{repo}
	RemoveRepoExemption(ctx context.Context, params RemoveRepoExemptionParams) (RemoveRepoExemptionRes, error)
	// RequirePasswordResetForPrincipal implements requirePasswordResetForPrincipal operation.
	//
	// Flags the specified principal so they must change their password on next login.
	//
	// POST /api/operator/principals/{principal}/require-password-reset
	RequirePasswordResetForPrincipal(ctx context.Context, params RequirePasswordResetForPrincipalParams) (RequirePasswordResetForPrincipalRes, error)
	// ResetOperatorPassword implements resetOperatorPassword operation.
	//
	// Self-service password reset. The operator must supply their current password for verification. On
	// success, the password-reset flag is cleared and all refresh tokens issued before this change are
	// invalidated.
	//
	// POST /api/operator/password
	ResetOperatorPassword(ctx context.Context, req *ChangePasswordReq) (ResetOperatorPasswordRes, error)
	// SetDefaultTier implements setDefaultTier operation.
	//
	// Set the platform default tier for new repos.
	//
	// POST /api/operator/tiers/{name}/set-default
	SetDefaultTier(ctx context.Context, params SetDefaultTierParams) (SetDefaultTierRes, error)
	// SetOperatorPrincipalPassword implements setOperatorPrincipalPassword operation.
	//
	// Admin-only. Sets a new password for the specified principal without requiring the current password.
	// If `invalidate` is true, the principal will be required to change their password on next login
	// (temporary password flow). Invalidates all existing refresh tokens for that principal.
	//
	// POST /api/operator/principals/{principal}/set-password
	SetOperatorPrincipalPassword(ctx context.Context, req *SetPrincipalPasswordReq, params SetOperatorPrincipalPasswordParams) (SetOperatorPrincipalPasswordRes, error)
	// SyncRepo implements syncRepo operation.
	//
	// Reconciles the cluster against the supplied app list. Apps present in the cluster but absent from
	// the list are queued for deletion. Equivalent to calling upsert for each listed app and delete for
	// each omitted one, in a single atomic request.
	//
	// POST /api/repos/{org}/{repo}/sync
	SyncRepo(ctx context.Context, req *SyncRepoReq, params SyncRepoParams) (SyncRepoRes, error)
	// TokenDeploy implements tokenDeploy operation.
	//
	// For use in CI/CD pipelines. Present a short-lived identity token issued by your CI platform (e.g. a
	// GitHub Actions OIDC token). Returns a scoped access token valid for the duration of the deploy.
	//
	// POST /api/token/deploy
	TokenDeploy(ctx context.Context, req *TokenDeployReq) (TokenDeployRes, error)
	// TokenOIDC implements tokenOIDC operation.
	//
	// For interactive operator sessions. Exchanges a platform credential for an access/refresh token pair.
	// Use the refresh endpoint to stay authenticated without re-presenting credentials.
	//
	// POST /api/token/oidc
	TokenOIDC(ctx context.Context, req *TokenOIDCReq) (TokenOIDCRes, error)
	// TokenRefresh implements tokenRefresh operation.
	//
	// Rotates both tokens. The supplied refresh token is immediately invalidated; use the new pair going
	// forward.
	//
	// POST /api/token/refresh
	TokenRefresh(ctx context.Context, req *TokenRefreshReq) (TokenRefreshRes, error)
	// UpdateOperatorConfig implements updateOperatorConfig operation.
	//
	// Applies the supplied fields over the current config. Omitted fields are left unchanged.
	//
	// PATCH /api/operator/config
	UpdateOperatorConfig(ctx context.Context, req *PlatformConfig) (UpdateOperatorConfigRes, error)
	// UpdateRepoTier implements updateRepoTier operation.
	//
	// Changes the resource tier for a repo, which controls its compute limits and cost ceiling. Promotion
	// to a higher tier may require additional approval depending on platform policy.
	//
	// PATCH /api/operator/repos/{org}/{repo}
	UpdateRepoTier(ctx context.Context, req *UpdateRepoTierReq, params UpdateRepoTierParams) (UpdateRepoTierRes, error)
	// UpdateTier implements updateTier operation.
	//
	// Updates one or more fields on a tier. Changes are propagated immediately to all app namespaces on
	// that tier.
	//
	// PATCH /api/operator/tiers/{name}
	UpdateTier(ctx context.Context, req *UpdateTierReq, params UpdateTierParams) (UpdateTierRes, error)
	// UpsertApp implements upsertApp operation.
	//
	// Creates or updates an app. Runs a staging handshake to validate the image before applying the
	// manifest. Some changes may require operator approval and will appear in the pending_approval field
	// of the response.
	//
	// POST /api/repos/{org}/{repo}/apps
	UpsertApp(ctx context.Context, req *AppSpec, params UpsertAppParams) (UpsertAppRes, error)
	// WakeApp implements wakeApp operation.
	//
	// Scales the app back up from zero replicas. Use this to pre-warm the app before expected traffic
	// rather than waiting for the first request to trigger wake-on-demand.
	//
	// POST /api/repos/{org}/{repo}/apps/{name}/wake
	WakeApp(ctx context.Context, params WakeAppParams) (WakeAppRes, error)
	// NewError creates *ErrorInternalServerStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorInternalServerStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
